spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.10
    port: 6379
  session:
    store-type: redis
server:
  port: 20001
  servlet:
    session:
      timeout: 30m

#      使用spring.session需要进行配置  30分钟
#      server:
#        servlet:
#          session:
#            timeout: 30m