spring:
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.56.10
    port: 5672
    virtual-host: /
  application:
    name: gulimall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.56.10
    port: 6379
  session:
    store-type: redis
server:
  port: 10001
  servlet:
    session:
      timeout: 30m