spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tSNRBjvxzyAU79DNi1i
      secret-key: P1xrqfPN4a9zKkxpkwAht5VKenvvRx
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: helianthusmall
      sms:
        host: https://jmsms.market.alicloudapi.com
        path: /sms/send
        appcode: 304e22bb4ded4c6d812c40133ff41b0c
server:
  port: 30000

